---
- name: Deploy BookMyShow App to Kubernetes
  hosts: localhost
  connection: local
  tasks:
    - name: Restart Kubernetes Deployment
      shell: kubectl rollout restart deployment bms-app
      register: deploy_result

    - name: Show deployment status
      debug:
        var: deploy_result.stdout
