---
- name: Deploy to EKS using kubectl
  hosts: localhost
  tasks:
    - name: Apply deployment and service
      shell: |
        kubectl apply -f deployment.yml
        kubectl apply -f service.yml
        kubectl rollout status deployment/bms-app
