apiVersion: apps/v1
kind: Deployment
metadata:
  name: bms-app
  labels:
    app: bms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bms
  template:
    metadata:
      labels:
        app: bms
    spec:
      imagePullSecrets:
      - name: ecr-secret  # <--- ADD THIS SECTION
      containers:
      - name: bms-container
        image: 372714115180.dkr.ecr.ap-south-1.amazonaws.com/bms:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
